title when sharing note
fleetingnotes/fleeting-notes-flutter pull request #738
Opened 2023-07-26 01:26 UTC by gonzalovelasco

2023-07-28 14:43 UTC, matthewwong525 commented on lib/screens/note/components/note_editor_app_bar.dart
> +    String concatenatedText = title != null ? "$title\n$content" : content;
good work on this!

2023-07-28 14:51 UTC, matthewwong525 commented on lib/screens/note/components/note_editor_app_bar.dart
> +      await Clipboard.setData(ClipboardData(text: content));
this should include the title as well `$title\n$content`

2023-07-28 15:01 UTC, matthewwong525 requested changes
When sharing from web, it should include the title as well!

2023-07-28 16:42 UTC, gonzalovelasco commented on lib/screens/note/components/note_editor_app_bar.dart
> +      await Clipboard.setData(ClipboardData(text: content));
Fixed 502ad25f4d55a6edd7ce568f81226b93b559e5ae

2023-07-29 13:47 UTC, matthewwong525 approved these changes
LGTM

2023-07-29 13:47 UTC, merged