Trash notes screen
fleetingnotes/fleeting-notes-flutter pull request #841
Opened 2023-08-08 22:34 UTC by gonzalovelasco

<img width="767" alt="Screenshot 2023-08-08 at 19 33 25" src="https://github.com/fleetingnotes/fleeting-notes-flutter/assets/3978399/20469440-8081-497c-bb2b-5f238a66b007">
<img width="1101" alt="Screenshot 2023-08-08 at 19 33 56" src="https://github.com/fleetingnotes/fleeting-notes-flutter/assets/3978399/b80e0e5c-394c-489c-bae4-ea3c796de661">
<img width="1150" alt="Screenshot 2023-08-08 at 19 33 39" src="https://github.com/fleetingnotes/fleeting-notes-flutter/assets/3978399/1336b857-9160-46ba-9f07-ca5de8054ffb">

2023-08-10 17:30 UTC, matthewwong525 commented on lib/screens/main/components/side_rail.dart
> -  final VoidCallback addNote;
great job cleaning this up!

2023-08-10 17:42 UTC, matthewwong525 approved these changes

2023-08-10 17:44 UTC, matthewwong525 requested changes
This is a pretty big feature, could you add some tests? for example:
- go to trash > see empty > go to main delete note > go to trash > see note
- (and another for restore note)

just cover these 2 main use cases in tests. thanks and great work. apart from tests things look good

2023-08-14 18:33 UTC, gonzalovelasco commented
> This is a pretty big feature, could you add some tests? for example:
> 
> * go to trash > see empty > go to main delete note > go to trash > see note
> * (and another for restore note)
> 
> just cover these 2 main use cases in tests. thanks and great work. apart from tests things look good

Tests added a45c6070a7ac7e7dd401c1f4778c5749cbc2fe76

2023-08-15 01:50 UTC, matthewwong525 approved these changes
LGTM

2023-08-15 01:51 UTC, merged