[WIP] - Save searches
fleetingnotes/fleeting-notes-flutter pull request #869
Opened 2023-08-11 17:27 UTC by gonzalovelasco

<img width="345" alt="Screenshot 2023-08-11 at 14 26 46" src="https://github.com/fleetingnotes/fleeting-notes-flutter/assets/3978399/cb0aca1b-ec3a-45eb-931c-e68ef475b0f7">
<img width="341" alt="Screenshot 2023-08-11 at 14 27 22" src="https://github.com/fleetingnotes/fleeting-notes-flutter/assets/3978399/bee5fcc7-e693-4e11-baa6-11732c1eea53">

2023-08-14 14:33 UTC, matthewwong525 commented
make the UI look like Google Keep, add divider and a title saying saved saerches + a button to "Create/Edit" ?

2023-08-16 20:55 UTC, matthewwong525 requested changes
Great work! just a few small changes from me

2023-08-16 20:55 UTC, matthewwong525 commented on lib/screens/main/components/create_search_dialog.dart
> +            Padding(
remove the done button

2023-08-16 20:55 UTC, matthewwong525 commented on lib/screens/main/components/create_search_dialog.dart
> +                      decoration: const InputDecoration(hintText: 'New search'),
```suggestion
                      decoration: const InputDecoration(hintText: 'Create new search'),
```

2023-08-16 20:55 UTC, matthewwong525 commented on lib/screens/main/components/create_search_dialog.dart
> +                      'Create/Edit Searches',
```suggestion
                      'Edit searches',
```

2023-08-16 20:55 UTC, matthewwong525 commented on lib/screens/main/components/create_search_dialog.dart
> +                  return ListTile(
Add leading search icon like in Google Keep

![IMG_4FCF7D1E336E-1](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/80706a39-fea9-4b7b-bd0d-a7d3e4a55b34)

2023-08-16 21:11 UTC, gonzalovelasco commented on lib/screens/main/components/create_search_dialog.dart
> +            Padding(
Fixed 49a0cb7beb988f0e6a0251f475efd8a2b4291948

2023-08-17 12:52 UTC, gonzalovelasco commented on lib/screens/main/components/create_search_dialog.dart
> +                  return ListTile(
183ef22ce96cf4181009785c03ae5b0ec8e98b77

2023-08-21 16:18 UTC, matthewwong525 approved these changes
LGTM, great work gonzalo! Merge if you're happy with it!

2023-08-25 17:02 UTC, merged