New checklist feature
fleetingnotes/fleeting-notes-flutter pull request #898
Opened 2023-08-23 13:19 UTC by gonzalovelasco

2023-08-25 17:12 UTC, matthewwong525 requested changes
also disable markdown preview when in this mode because that breaks the checklist. (i.e. hide this button:
![image](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/be433c48-5270-4969-991d-589cafd2078a)

2023-08-25 17:12 UTC, matthewwong525 commented on lib/screens/note/components/CheckListField/check_list_field.dart
> +                    child: TextField(
maxLines should be 1 and clicking enter should go to the next field, I tried clicking enter and it did this which should not be the expected behaviour
![image](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/252e1a34-cb7a-4d46-b105-31f5dfd95f5e)

2023-08-25 17:27 UTC, matthewwong525 commented
only open checklist view if checklist is empty (when clicking from mobile toolbar)

2023-08-25 17:28 UTC, matthewwong525 commented
Also, when you click the checklist is first populated it should have autofocus!
1. Click checklist button
2. Focus should be within the checklist textfield

2023-08-25 17:37 UTC, matthewwong525 commented
also, could you take a look into this bug:
![Export-1692985030215](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/614f03f2-20e8-40d0-828a-50e74b65535c)

2023-08-25 19:09 UTC, gonzalovelasco commented on lib/screens/note/components/CheckListField/check_list_field.dart
> +                    child: TextField(
Fixed 1e3b16f59c1d52a48c7f99d13cadf63c0a728169

2023-08-25 19:12 UTC, gonzalovelasco commented
> only open checklist view if checklist is empty (when clicking from mobile toolbar)

673f54fb0e9d3f600f2eebdd1b6a1c720628b05c

2023-08-28 17:36 UTC, gonzalovelasco commented
> Also, when you click the checklist is first populated it should have autofocus!
> 
> 1. Click checklist button
> 2. Focus should be within the checklist textfield

4d6d1fd057f6a599802ed1076f7f772ee489db9a

2023-08-29 16:34 UTC, matthewwong525 requested changes
two things to change:
1. Typing in a new field should not open and close the keyboard
2. When i click next /enter on the keyboard it should go to the next text field. (similar to google keep mobile)
3. when i click backspace and checklistitem is not the first checklist textfield then it'll delete it (similar to google keep mobile)
4. when i click ba

2023-08-29 19:26 UTC, matthewwong525 commented
look at my changes and apart from that LGTM

2023-08-30 22:58 UTC, matthewwong525 approved these changes
LGTM

2023-08-30 22:58 UTC, merged