Fix empty checklist markdown
fleetingnotes/fleeting-notes-flutter pull request #906
Opened 2023-08-31 16:18 UTC by gonzalovelasco

2023-08-31 16:43 UTC, matthewwong525 requested changes
When creating from an empty note in edit mode, it should create a new list item (I only see + LIst item button, no place to input text for checklist) but it doesn't. See below also my other comments. Apart from these, good job gonzalo. Im proud of you!
![Export-1693500176198](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/beff626f-7abd-439c-9048-adcf708c464d)

2023-08-31 16:43 UTC, matthewwong525 commented on lib/screens/note/note_editor.dart
> +      widget.onCheckListEnabled!();
```suggestion
      widget.onCheckListEnabled?.call();
```

2023-08-31 16:43 UTC, matthewwong525 commented on lib/screens/note/note_editor.dart
> +      widget.onCheckListEnabled!();
let's avoid using the ! . it breaks things.

2023-08-31 16:43 UTC, matthewwong525 commented on lib/screens/note/note_editor.dart
> -  bool onChecklistPressed() {
changing this breaks a change i made in the content field. see gif below. maybe solution is passing the state into the contentfield, you can decide how it should be done. also can you add a test for this as well?
![Export-1693499925469](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/422f8898-af8a-45bb-bfcd-1332d61fde5c)

2023-08-31 18:07 UTC, gonzalovelasco commented
> When creating from an empty note in edit mode, it should create a new list item (I only see + LIst item button, no place to input text for checklist) but it doesn't. See below also my other comments. Apart from these, good job gonzalo. Im proud of you! ![Export-1693500176198](https://user-images.githubusercontent.com/20890995/264715318-beff626f-7abd-439c-9048-adcf708c464d.gif)

Fixed 09a58e0544bc049ec9ca08c5b9b0a46841860d04

2023-09-01 17:44 UTC, matthewwong525 approved these changes
LGTM, give it a look thru

2023-09-01 18:53 UTC, matthewwong525 requested changes
almost there, good work finding this workaround!

2023-09-01 18:53 UTC, matthewwong525 commented on lib/screens/note/note_editor.dart
> +    return contentController.text
```suggestion
    // TODO: fix work around (https://github.com/fleetingnotes/fleeting-notes-flutter/pull/906)
    return contentController.text
```

2023-09-01 18:53 UTC, matthewwong525 commented on lib/screens/note/note_editor.dart
> +        .replaceAll(RegExp(r"- \[ \] ?(\n|$)"), "- [ ]\n");
This doesn't handle the case where the checkbox is ticked `- [x]`

2023-09-01 19:20 UTC, gonzalovelasco commented on lib/screens/note/note_editor.dart
> +        .replaceAll(RegExp(r"- \[ \] ?(\n|$)"), "- [ ]\n");
Fixed 06d56fbb3fb9dc2036429c7a6473bd8a1b9f56cd

2023-09-01 19:20 UTC, gonzalovelasco commented on lib/screens/note/note_editor.dart
> +    return contentController.text
Fixed 06d56fbb3fb9dc2036429c7a6473bd8a1b9f56cd

2023-09-01 19:22 UTC, matthewwong525 approved these changes
LGTM

2023-09-01 19:44 UTC, merged