Preserve state between opening and closing notes
fleetingnotes/fleeting-notes-flutter pull request #907
Opened 2023-09-02 18:06 UTC by MerlimarCode

2023-09-03 05:49 UTC, matthewwong525 commented on test/checklist_field_test.dart
> +      // await tester.tap(find.byIcon(Icons.edit));
what's the reasoning for commenting this out? :O

2023-09-03 05:51 UTC, matthewwong525 commented on lib/screens/note/note_editor_screen.dart
>        previewEnabled = true;
because you added it in the settings, i believe we can just get rid of this variable now. it's redundant

2023-09-03 05:52 UTC, matthewwong525 requested changes
Great work marlond! Just a few changes and should be good!

2023-09-03 06:13 UTC, MerlimarCode commented on lib/screens/note/note_editor_screen.dart
>        previewEnabled = true;
It breaks without it, is there something I missed with putting it into the settings?

2023-09-05 21:10 UTC, matthewwong525 approved these changes

2023-09-05 21:10 UTC, matthewwong525 commented on lib/screens/note/note_editor_screen.dart
> +    final settings = ref.watch(settingsProvider);
```suggestion
    final settings = ref.read(settingsProvider);
```

2023-09-06 03:44 UTC, matthewwong525 approved these changes
great work lgtm

2023-09-06 03:44 UTC, merged